### ISSUE TITLE
Incompatible baselines ?

### ISSUE THREAD

**Issue by perone** [fsschneider/DeepOBS#27]
Hi, thanks for the project, it's really handy! I tried to use the released `1.2.0-beta0` version as well as the `master` with the baselines from this repository: https://github.com/fsschneider/DeepOBS_Baselines without success, I always get the same error:

```
(...)
File "/deepobs/analyzer/shared_utils.py", line 118, in aggregate_runs
    aggregate["optimizer_hyperparams"] = json_data["optimizer_hyperparams"]
KeyError: 'optimizer_hyperparams'
```

Are there any baselines that are supported by the version with PyTorch support as well ?

---

**To Do**

We will do the following steps for version 1.2.0:

- [ ] Provide extensive baselines for version 1.2.0.

**Comment by fsschneider** [comment]
Hi,

thanks for giving DeepOBS a try!

Yes, the baselines and the `1.2.0-beta0` release are indeed incompatible. The first (minor) reason is that we slightly changed the way we write our log files. This is why you are getting the mentioned `KeyError`. This could be fixed rather easily.
More important though, the baselines are incompatible because they were created with a different `minor` version of DeepOBS (version `1.1` vs. version `1.2`). If two versions differ in the second digit, this means that we made large enough changes to the code, such that they could change the results.
As an example, we reduced the size of the `training set` with version `1.2.0-beta0` to accommodate an additional `validation set`. This will most likely have an effect on the results and thus the baselines.
For this reason, you should not use `1.1.XX` baselines while using version `1.2.XX` of DeepOBS.

We are currently in the process of collecting baselines for the `1.2` version. As they will be much more extensive than what we offer for version `1.1`, they also take a lot longer to run. 

If you don't need any functionality from version `1.2` (such as the PyTorch support), you can just use version `1.1` (from the `master`) and use the baselines you mentioned. If you do however need to use version `1.2` and need baselines, send me an email. I'll see if I can offer you some (as of yet) incomplete preview of the new baselines.

**Comment by perone** [comment]
Thanks for the answer @fsschneider ! I'll be using the 1.2 (because of PyTorch), but I can wait for the baselines, no problem. Thanks for open sourcing the baselines !

**Comment by fsschneider** [comment]
We now have a much more extensive collection of baselines for version `1.2.0`.

Check it out at https://github.com/SirRob1997/Descending-through-a-Crowded-Valley---Results.

**Comment by perone** [comment]
Great work, thanks @fsschneider !
